Song report
FUCT-K15-SE1501/4kTiles-Backend pull request #25
Opened 2022-02-11 03:36 UTC by quocan17102000

add song report

2022-02-11 13:26 UTC, tunbk1002 requested changes

2022-02-11 13:26 UTC, tunbk1002 commented on Controllers/SongController.cs
> +        /// <returns></returns>
Reason for editing song controller?

2022-02-11 13:26 UTC, tunbk1002 commented on Controllers/SongController.cs
> +        /// <returns></returns>
Reason for editing song controller?

2022-02-11 13:26 UTC, tunbk1002 commented on Controllers/SongReportsController.cs
> +        public async Task<ActionResult<IEnumerable<SongReport>>> GetSongReports()
ActionResult or IActionResult?

2022-02-11 13:26 UTC, tunbk1002 commented on Controllers/SongReportsController.cs
> +        public async Task<ActionResult<SongReport>> GetSongReport(int id)
ActionResult or IActionResult?

2022-02-11 13:26 UTC, tunbk1002 commented on Controllers/SongReportsController.cs
> +        public async Task<IActionResult> PutSongReport(int id, SongReport songReport)
ActionResult or IActionResult?

2022-02-11 13:26 UTC, tunbk1002 commented on Controllers/SongReportsController.cs
> +        public async Task<ActionResult<SongReport>> PostSongReport(SongReport songReport)
ActionResult or IActionResult?

2022-02-11 13:26 UTC, tunbk1002 commented on Controllers/SongReportsController.cs
> +        public async Task<IActionResult> DeleteSongReport(int id)
ActionResult or IActionResult?

2022-02-11 13:26 UTC, tunbk1002 commented on Controllers/SongReportsController.cs
> +        private bool SongReportExists(int id)
Controller have non-routing function?

2022-02-11 13:26 UTC, tunbk1002 commented on DataObjects/DAO/Song/CreateSongDAO.cs
> +
Reason editing this DAO?

2022-02-11 13:26 UTC, tunbk1002 commented on DataObjects/DAO/Song/EditSongDAO.cs
> +}
Reason editing this DAO?

2022-02-11 13:26 UTC, tunbk1002 commented on DataObjects/DTO/Library/LibraryFilterDTO.cs
> +
Reason editing this DTO?

2022-02-11 13:26 UTC, tunbk1002 commented on DataObjects/DTO/Library/LibraryGenreDTO.cs
> +
Reason editing this DTO?

2022-02-11 13:26 UTC, tunbk1002 commented on DataObjects/DTO/Library/LibraryUserIdDTO.cs
> +
Reason editing this DTO?

2022-02-11 13:26 UTC, tunbk1002 commented on DataObjects/DTO/Pagination/PaginationResponse.cs
> +
Reason editing this?

2022-02-11 13:26 UTC, tunbk1002 commented on DataObjects/DTO/SongDTO/EditSongDTO.cs
> +
Reason editing this DTO?

2022-02-11 13:26 UTC, tunbk1002 commented on Helpers/HashHelper.cs
> +}
Reason editing this?

2022-02-11 13:26 UTC, tunbk1002 commented on Helpers/PaginationHelper.cs
> +
Reason editing this?

2022-02-11 13:26 UTC, tunbk1002 commented on Mappers/SongProfile.cs
> +
Reason editing this?

2022-02-12 08:07 UTC, HSGamer requested changes
Do not reformat other files, just do your work.

2022-02-16 08:07 UTC, HSGamer commented
Thiếu Mapper Profile cho các DTO và DAO.
Controller không được phép dùng DAO như là tham số, chỉ dùng DTO để mapper map sang DAO cho service.
Chưa nâng cấp lên .NET 6 (có nhiều file bị chỉnh thừa).
Chỉ làm report, không đụng đến các service khác, có chỉnh thì kêu tác giả service đó chỉnh.

2022-02-17 05:36 UTC, closed without merging